name: carotv
description: A TV application by ClassicTech.
publish_to: 'none'


version: 1.0.0+1
# Major [Drastic]. Patch[Add/removal]. [minor-changes] + [Build Number]

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9

  permission_handler: ^11.0.1
  upgrader: ^9.0.0
  equatable: ^2.0.5
  lottie: ^2.7.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^2.3.8
  dartz: ^0.10.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.10
  flutter_hooks: ^0.20.4
  flutter_screenutil: ^5.9.0
  flutter_form_builder: ^9.2.0
  form_builder_validators: ^9.1.0
  awesome_snackbar_content: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/

fonts:
  - family: GilroyThin
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Thin.ttf

  - family: GilroyUltraLight
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf

  - family: GilroyLight
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Light.ttf

  - family: GilroyRegular
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Regular.ttf

  - family: GilroyMedium
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Medium.ttf

  - family: GilroySemiBold
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf

  - family: GilroyBold
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Bold.ttf


  - family: GilroyExtraBold
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf

  - family: GilroyBlack
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Black.ttf